version: "3.8"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    environment:
      - CLUSTER_NAME=bigdata_cluster
      - NAMENODE_HOSTNAME=namenode
    ports:
      - "9870:9870"  # Web UI HDFS
      - "8020:8020"  # RPC HDFS (modifié pour correspondre à ta configuration)
    volumes:
      - namenode:/hadoop/dfs/name
    networks:
      bigdata:
        aliases:
          - namenode.bigdata

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    hostname: datanode1
    environment:
      - CLUSTER_NAME=bigdata_cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020  # Mis à jour pour correspondre au port 8020
      - HDFS_NAMENODE=namenode
    ports:
      - "9865:9864"  # datanode2 UI
    volumes:
      - datanode1:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      bigdata:
        aliases:
          - datanode1

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    hostname: datanode2
    environment:
      - CLUSTER_NAME=bigdata_cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_NAMENODE=namenode
    ports:
      - "9866:9864"  # datanode2 UI
    volumes:
      - datanode2:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      bigdata:
        aliases:
          - datanode2

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    hostname: resourcemanager
    environment:
      - CLUSTER_NAME=bigdata_cluster
      - YARN_RESOURCEMANAGER_HOSTNAME=resourcemanager
    ports:
      - "8088:8088"
    depends_on:
      - namenode
    networks:
      bigdata:
        aliases:
          - resourcemanager

  spark-master:
    image: bitnami/spark:3.3.1
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    ports:
      - "7077:7077"      # Spark master port
      - "8080:8080"      # Spark master web UI
    volumes:
      - ./SalaryModel:/app
    networks:
      bigdata:
        aliases:
          - spark-master
  
  spark-worker1:
    image: bitnami/spark:3.3.1
    container_name: spark-worker1
    hostname: spark-worker1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_WEBUI_PORT=8081
    depends_on:
      - spark-master
    ports:
      - "8081:8081"      # Spark worker web UI
    volumes:
      - ./SalaryModel:/app
    networks:
      bigdata:
        aliases:
          - spark-worker1


volumes:
  namenode:
  datanode1:
  datanode2:

networks:
  bigdata:
    driver: bridge
    name: bigdata
  